services:
  - type: web
    name: megalodon
    env: docker
    plan: free
    branch: main
    repo: https://github.com/DybyTechX/MEGALODON-SESSION-ID
    dockerfilePath: ./Dockerfile
    autoDeploy: true
